### ISSUE TITLE
Microcosm Vagrant custom box

### ISSUE THREAD

**Issue by rajeevaroraau** [SLS-ALL/devops-microcosm#1]
The Microcosm vagrant custom box that this pipeline uses is no longer available on CMU's Box (as in Box file sharing) shared folder.  As a result it is not possible to build the environment.

Any alternatives?  Possibly a specification of the custom box, or may be share it here.

**Comment by Lone1567** [comment]
Hi Rajeev,

I have updated the URL and checksum in the "metadata.json" file to point to the new box location of the cmu/centos72_x86_64 version 0.1.0 box. I have tested it on a separate machine to ensure that the download completes.

Thanks for pointing out the issue!

Best,

Shane

**Comment by rajeevaroraau** [comment]
Thanks very much Shane.  Works like magic.
