### ISSUE TITLE
gitlab node failing on chef recipies 

### ISSUE THREAD

**Issue by deejay-sl** [SLS-ALL/devops-microcosm#3]
Not sure what is going on here as it was working for me a few days ago; I then blew away everything, rebuilt and am now running into this:

==> gitlab:   * file[/opt/gitlab/sv/postgres-exporter/supervise/ok] action touch (skipped due to only_if)
==> gitlab:   * file[/opt/gitlab/sv/postgres-exporter/log/supervise/ok] action touch (skipped due to only_if)
==> gitlab:   * file[/opt/gitlab/sv/postgres-exporter/supervise/control] action touch (skipped due to only_if)
==> gitlab:   * file[/opt/gitlab/sv/postgres-exporter/log/supervise/control] action touch (skipped due to only_if)
==> gitlab:   * service[postgres-exporter] action nothing (skipped due to action :nothing)
==> gitlab:   * template[/var/opt/gitlab/postgres-exporter/queries.yaml] action create (up to date)
==> gitlab:
==> gitlab: Running handlers:
==> gitlab: Running handlers complete
==> gitlab: Chef Client finished, 3/515 resources updated in 03 minutes 40 seconds
==> gitlab: STDERR:
==> gitlab: ---- End output of "bash"  "/tmp/chef-script20180306-12463-4pjban" ----
==> gitlab: Ran "bash"  "/tmp/chef-script20180306-12463-4pjban" returned 1
==> gitlab: [2018-03-06T16:55:47-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by Lone1567** [comment]
Hello!

Thank you for filing this issue. Are you using the VM version of Microcosm or the Docker version?

Thanks,

Shane

**Comment by Lone1567** [comment]
Hello Deejay,

I was unable to replicate the issue. For both the strictly VM and microservice versions, I was successfully able to stand up the gitlab service without any errors. Are you still encountering this issue?

Thanks,

Shane

**Comment by tpalko** [comment]
Deejay, I don't see any error reported in the body of the chef run, and it does report "finished" at least for gitlab. Can you post the entirety of the chef output?

**Comment by Lone1567** [comment]
I'm going to mark this issue as resolved due to lack of replication and response.
